version: '3'

services:
  mongo:
    image: mongo
    container_name: ca-mongo
    restart: unless-stopped
    volumes:
      - ./db:/data/db
    logging:
      driver: none
  idxMongo:
    image: mongo
    container_name: ca-idx
    links:
      - mongo
    volumes:
      - ./config:/config
    command:
      - /config/run_idx.sh
    depends_on:
      - mongo
  bindaas:
    image: camicroscope/bindaas:latest
    depends_on:
      - "mongo"
    container_name: ca-data
    restart: unless-stopped
    logging:
      driver: none
    ports: ["8080:8080", "9099:9099"]
    volumes:
      - ./config/bindaas_projects/:/root/bindaas/bin/projects/
      - ./config/bindaas.config.json:/root/bindaas/bin/bindaas.config.json
  iip:
    image: camicroscope/iipimage:latest
    container_name: ca-iip
    restart: unless-stopped
    volumes:
      - ./images/:/data/images/
  security:
    image: camicroscope/security:latest
    container_name: ca-security
    restart: unless-stopped
    ports: ["4010:4010"]
    volumes:
      - ./config/pathdb_routes.json:/root/src/routes.json
    environment:
      - DISABLE_SEC=true
  auth:
    image: camicroscope/auth_service:latest
    container_name: ca-auth
    logging:
      driver: none
  pathdb:
    image: camicroscope/pathdb:latest
    container_name: quip-pathdb
    restart: unless-stopped
    ports: ["443:443","80:80"]
    volumes:
      - ./data:/data/
      - ./images/:/data/pathdb/files/wsi
      - ./config/pathdb:/quip/web/sites/default
      - ./jwt_keys/:/keys/
      - ./config:/config
    command:
      - /config/pathdb_pre.sh
  imageloader:
    image: camicroscope/pathdb-imageloader:latest
    container_name: quip-imageloader
    volumes:
      - ./data:/data/
      - ./images:/data/images
  segloader:
    image: camicroscope/pathdb-segloader:latest
    container_name: quip-segloader
    volumes:
      - ./data:/data
  heatmaploader:
    image: camicroscope/pathdb-heatmaploader:latest
    container_name: quip-hmloader
    ports: ["27017:27017"]
    volumes:
      - ./data:/mnt/data/
