apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: quip-featuredb-img
    name: quip-featuredb-img
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: quip-featuredb-img
    name: quip-featuredb-img
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: quip-featuredb-img:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: prism
        uri: https://github.com/SBU-BMI/quip_featuredb.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: mongo:3.6.18-xenial
          namespace: my-test
      type: Docker
    triggers:
    - github:
        secret: e9ZBK4w3F8GMNlWqjnkM
      type: GitHub
    - generic:
        secret: QY1ZH7We-RN_0v_CNMhG
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}
